name: Tests
on: [push]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-18.04
    steps:
      - name: Notify commit
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 16777215
        run: "curl -X POST -d \"{\\\"embeds\\\": [{\\\"title\\\": \\\"Update pushed (${GITHUB_REF})\\\", \\\"color\\\": ${COLOUR}, \\\"fields\\\": [{\\\"name\\\": \\\"See changes\\\", \\\"value\\\": \\\"https://github.com/arco-tech/audit_web_sdk/commit/${GITHUB_SHA}\\\"}, {\\\"name\\\": \\\"See workflow\\\", \\\"value\\\": \\\"https://github.com/arco-tech/audit_web_sdk/commit/${GITHUB_SHA}/checks\\\"}]}]}\" -H \\\"Content-Type: application/json\\\" ${WEBHOOK_URL}"

      - name: Setup
        uses: actions/setup-node@master

      - name: Notify setup failure
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 15086157
          MESSAGE: "Setup failure"
        run: "curl -X POST -d \"{\\\"embeds\\\": [{\\\"title\\\": \\\"${MESSAGE}\\\", \\\"color\\\": ${COLOUR}}]}\" -H \\\"Content-Type: application/json\\\" ${WEBHOOK_URL}"

      - name: Checkout
        uses: actions/checkout@v1

      - name: Notify checkout failure
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 15086157
          MESSAGE: "Checkout failure"
        run: "curl -X POST -d \"{\\\"embeds\\\": [{\\\"title\\\": \\\"${MESSAGE}\\\", \\\"color\\\": ${COLOUR}}]}\" -H \\\"Content-Type: application/json\\\" ${WEBHOOK_URL}"

      - name: Install
        run: npm install

      - name: Notify install failure
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 15086157
          MESSAGE: "Install failure"
        run: "curl -X POST -d \"{\\\"embeds\\\": [{\\\"title\\\": \\\"${MESSAGE}\\\", \\\"color\\\": ${COLOUR}}]}\" -H \\\"Content-Type: application/json\\\" ${WEBHOOK_URL}"

      - name: Test
        env:
          API_ENDPOINT: "https://test.dt.arco.nz"
        run: TEST_OUTPUT=$(npm test 2>&1)

      - name: Notify test failure
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 15086157
          MESSAGE: "Test failure"
        run: "curl -X POST -d \"{\\\"embeds\\\": [{\\\"title\\\": \\\"${TEST_OUTPUT}\\\", \\\"color\\\": ${COLOUR}}]}\" -H \\\"Content-Type: application/json\\\" ${WEBHOOK_URL}"

      - name: Notify test success
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 8638247
          MESSAGE: "Tests successful"
        run: "curl -X POST -d \"{\\\"embeds\\\": [{\\\"title\\\": \\\"${MESSAGE}\\\", \\\"color\\\": ${COLOUR}}]}\" -H \\\"Content-Type: application/json\\\" ${WEBHOOK_URL}"
