name: Tests
on: [push]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-18.04
    steps:
      - name: Notify commit
        env:
          COLOUR: 16777215
          MESSAGE: "Repo pushed"
        run: "curl -X POST -d '{\"embeds\": [{\"title\": \"${MESSAGE}\", \"color\": ${COLOUR}}]}' -H \"Content-Type: application/json\" ${DISCORD_WEBHOOK_URL}"

      - name: Setup
        uses: actions/setup-node@master

      - name: Notify setup failure
        if: failure()
        env:
          COLOUR: 15086157
          MESSAGE: "Action setup failure"
        run: "curl -X POST -d '{\"embeds\": [{\"title\": \"${MESSAGE}\", \"color\": ${COLOUR}}]}' -H \"Content-Type: application/json\" ${DISCORD_WEBHOOK_URL}"

      - name: Checkout
        uses: actions/checkout@v1

      - name: Notify setup failure
        if: failure()
        env:
          COLOUR: 15086157
          MESSAGE: "Action checkout failure"
        run: "curl -X POST -d '{\"embeds\": [{\"title\": \"${MESSAGE}\", \"color\": ${COLOUR}}]}' -H \"Content-Type: application/json\" ${DISCORD_WEBHOOK_URL}"

      - name: Install
        run: npm install

      - name: Notify install failure
        if: failure()
        env:
          COLOUR: 15086157
          MESSAGE: "Action install failure"
        run: "curl -X POST -d '{\"embeds\": [{\"title\": \"${MESSAGE}\", \"color\": ${COLOUR}}]}' -H \"Content-Type: application/json\" ${DISCORD_WEBHOOK_URL}"

      - name: Test
        env:
          API_ENDPOINT: "https://test.dt.arco.nz"
        run: npm test

      - name: Notify test failure
        if: failure()
        env:
          COLOUR: 15086157
          MESSAGE: "Action test failure"
        run: "curl -X POST -d '{\"embeds\": [{\"title\": \"${MESSAGE}\", \"color\": ${COLOUR}}]}' -H \"Content-Type: application/json\" ${DISCORD_WEBHOOK_URL}"

      - name: Notify test success
        env:
          COLOUR: 8638247
          MESSAGE: "Action test successful"
        run: "curl -X POST -d '{\"embeds\": [{\"title\": \"${MESSAGE}\", \"color\": ${COLOUR}}]}' -H \"Content-Type: application/json\" ${DISCORD_WEBHOOK_URL}"
