name: Tests
on: [push]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-ubuntu-18.04
    steps:
      - name: Test
        env:
          API_ENDPOINT: "https://test.dt.arco.nz"
        uses: actions/setup-node@master
        run: "npm install && npm test"
