name: Tests
on: [push]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-ubuntu-18.04
    steps:
      - id: setup
        name: Setup
        uses: actions/setup-node@master
      - id: test
        name: Test
        env:
          API_ENDPOINT: "https://test.dt.arco.nz"
        run: npm install && npm test
