name: Tests
on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Notify commit
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 16777215
        run: "curl -X POST -d \"{\\\"embeds\\\": [{\\\"title\\\": \\\"Update pushed ($GITHUB_REF)\\\", \\\"color\\\": 16777215, \\\"fields\\\": [{\\\"name\\\": \\\"See changes\\\", \\\"value\\\": \\\"https://github.com/arco-tech/audit_web_sdk/commit/$GITHUB_SHA\\\"}, {\\\"name\\\": \\\"See workflow\\\", \\\"value\\\": \\\"https://github.com/arco-tech/audit_web_sdk/commit/$GITHUB_SHA/checks\\\"}]}]}\" -H \"Content-Type: application/json\" ${WEBHOOK_URL}"

      - name: Setup
        uses: actions/setup-node@master

      - name: Install
        run: npm install

      - name: Notify install failure
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 15086157
          MESSAGE: "Install failure"
        run: "curl -X POST -H \"Content-Type: application/json\" -d \"{\\\"embeds\\\": [{\\\"title\\\": \\\"$MESSAGE\\\", \\\"color\\\": $COLOUR}]}\" ${WEBHOOK_URL}"

      - name: Test
        env:
          API_ENDPOINT: "https://test.dt.arco.nz"
          TEST_OUTPUT: $
        run: npm test

      - name: Notify test failure
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 15086157
          MESSAGE: "Test failure"
        run: "curl -X POST -H \"Content-Type: application/json\" -d \"{\\\"embeds\\\": [{\\\"title\\\": \\\"$MESSAGE\\\", \\\"color\\\": $COLOUR}]}\" ${WEBHOOK_URL}"

      - name: Notify test success
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 8638247
          MESSAGE: "Tests successful"
        run: "curl -X POST -H \"Content-Type: application/json\" -d \"{\\\"embeds\\\": [{\\\"title\\\": \\\"$MESSAGE\\\", \\\"color\\\": $COLOUR}]}\" ${WEBHOOK_URL}"
