name: Tests
on: [push]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Notify commit
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 16777215
        run: "sudo ./bin/notify-commit"

      - name: Setup
        uses: actions/setup-node@master

      - name: Notify setup failure
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 15086157
          MESSAGE: "Setup failure"
        run: "sudo ./bin/notify $COLOUR \"$MESSAGE\""

      - name: Install
        run: npm install

      - name: Notify install failure
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 15086157
          MESSAGE: "Install failure"
        run: "sudo ./bin/notify $COLOUR \"$MESSAGE\""

      - name: Test
        env:
          API_ENDPOINT: "https://test.dt.arco.nz"
          TEST_OUTPUT: $
        run: npm test

      - name: Notify test failure
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 15086157
          MESSAGE: "Test failure"
        run: "sudo ./bin/notify $COLOUR \"$MESSAGE\""

      - name: Notify test success
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COLOUR: 8638247
          MESSAGE: "Tests successful"
        run: "sudo ./bin/notify $COLOUR \"$MESSAGE\""
